### ISSUE TITLE
Configure New Relic

### ISSUE THREAD

**Issue by Irio** [datasciencebr/jarbas#160]
https://newrelic.com/

**Comment by cuducos** [comment]
Do they have any free plan for open-source or something like that? Can you expand on what you have in mind here?

**Comment by decko** [comment]
Could NewRelic be substituted by Prometheus and Sentry? Prometheus could generate metrics around access, and Sentry could alert about any exception or problem around...

https://prometheus.io
https://getsentry.io

Sentry have a free plan for just one product using it, but it's a OSS and could be installed anywhere(also have docker images). 
Prometheus is also OSS, have docker images but I have no experience at all on how to install, run, etc...

**Comment by pedrommone** [comment]
@Decko NewRelic is kinda like Prometheus, but its not like Sentry.

If you guys want to monitor error logs and stuff, go ahead with Sentry, otherwise, if you guys want to monitor infrastructure and app performance and analytics, go ahead with NewRelic.

Usually, NewRelic and Sentry are a good match, I think you guys can apply for a free-tier (NewRelic).

**Comment by cuducos** [comment]
Close by inactivity — but anyone is free to re-open it if needed ; )
