### ISSUE TITLE
Split front-end (website) and backend (API endpoints)

### ISSUE THREAD

**Issue by leomeloxp** [datasciencebr/jarbas#18]

**Comment by cuducos** [comment]
Sorry, but what exactly you mean by that?

Currently Jarbas serves the site at [`/`](http://jarbas.datasciencebr.com/) and serves the API at [`/api/`](http://jarbas.datasciencebr.com/api/).

If you reach `/api/` as a human via browser [Django REST Framework](http://django-rest-framework.org) offers a human user-friendly UI, but if you reach it as a machine, via AJAX, `curl` etc. you get plain JSON:

```console
$ curl http://jarbas.datasciencebr.com/api/document/\?document_id\=5925678
{"count":1,"next":null,"previous":null,"results":[{"id":32782,"document_id":5925678,"congressperson_name":"CARMEN ZANOTTO","congressperson_id":164360,"congressperson_document":477,"term":2015,"state":"SC","party":"PPS","term_id":55,"subquota_number":5,"subquota_description":"Publicity of parliamentary activity","subquota_group_id":0,"subquota_group_description":"","supplier":"SIONEI RICARDO LEÃO DE ARAÚJO - MÍDIAS E IDENTIDADE","cnpj_cpf":"23782893000170","document_number":"0002","document_type":0,"issue_date":"2016-03-01T00:00:00","document_value":"5400.000","remark_value":"0.000","net_value":"5400.000","month":2,"year":2016,"installment":0,"passenger":"","leg_of_the_trip":"","batch_number":1267747,"reimbursement_number":5363,"reimbursement_value":"0.000","applicant_id":2433,"receipt_url":null,"receipt_fetched":false}]}
```

Yet the Jarbas itself is split in three apps:

* `jarbas/core`: core models, commands and URL configuration
* `jarbas/api`: the API (depends on `jarbas/core`)
* `jarbas/frontend`: the SASS & Elm front-end (independent of the other two apps, dependent on Django to compile SASS to CSS and Elm to JS)

As the front-end is _backend agnostic_ it could have its own repository and its own compile & deploy isolated from Django. But I think that as we're deploying to the same server, and as [we already miss a _devops_ to look after it](https://github.com/datasciencebr/jarbas/issues/12), keeping it (by now) in this repo is a good choice.

But I'm still not sure what was your point was about — would you mind expanding on it so we figure out how to improve Jarbas?

Many thanks,

**Comment by leomeloxp** [comment]
Oh wow, I had created this *issue* without a description. I then typed the whole description and probably forgot to submit/save 😂 Sorry for the totally unclear question 😑

Yeah, I meant breaking Jarbas into 2 (but as you now highlighted 3) repositories to make it easier to maintain.

Following up on your comment, I think it makes more sense to keep it all as a single repo for now, as there're no DevOps strategies in place. But to eventually break them up could be nice.

Lastly, I believe some of the server side rendering for the front-end is handled by Django/Python, correct? Would there be any motivation for adding some React on the front-end and maybe handling the data changes through AJAX or even server-side JS. At least for the React part, I believe it could make things easier when we came across into adding new functionality(eg, some advanced filtering of data) or even just improving bandwidth (sending across only JSON rather than full page markup after first page load).

That's more or less what I had in mind. Happy to keep the discussion going 🙂

**Comment by cuducos** [comment]
**1. Split backend & front-end**

Yes, in the future it makes sense. Now I'm afraid just adding nginx configs, shell scripts, instructions and git hooks to `contrib/` will make it a bigger mess — i.e will create technical debt.I really would like to see a proper solution for that. Maybe @luiz-simples can help us with Docker and stuff… and then we can afford a more solid infrastructure for development, provision and deployment — that's the perfect time for splitting the repo I guess: something like `jarbas-api` and `jarbas-frontend`.

Just a minor detail: no need to spit in three. Backend and front-end is enough. It is a merely a Django  architecture decision to keep some stuff in the core (`jarbas/core`) and some stuff in the API (`jarbas/api`), but they should be together on the backend repo.

**2. Fron-end**

> I believe some of the server side rendering for the front-end is handled by Django/Python […]

No. Python backend is merely compiling files (from `.sass` to `.css` and from `.elm` to `.js`). We could literally deploy a HTML together with the `.css` and `.js` to a S3 instance (I mean, something with no backend at all) and that would work.

> Would there be any motivation for adding some React on the front-end and maybe handling the data changes through AJAX or even server-side JS

100% of the data changes is managed in the front-end already (no UI rendering in the backend, no JS in the server-side).

> for the React part, I believe it could make things easier when we came across into adding new functionality(eg, some advanced filtering of data) or even just improving bandwidth (sending across only JSON rather than full page markup after first page load).

All that is currently handled through Elm. We are literally just _sending across only JSON rather than full page markup after first page load_ already : )

**Comment by luiz-simples** [comment]
Me passa o seu telefone ou liga pra mim. (48) 8810-8161
A ideia é Dockerrizar o seu projeto e automatizar o deploy via containers, o ideia é o build criar um container com a versão final de produção do seu projeto, seja ele fullstrack ou SPA.
Possível até versionar na nuvem esses containers, facilitando assim rollbacks nos deploys quando necessário.
Abraços.

**Comment by cuducos** [comment]
Closed by inactivity
