### ISSUE TITLE
Add .editorconfig file

### ISSUE THREAD

**Issue by pedrommone** [datasciencebr/jarbas#24]
In order to keep everything fine for everyone we need add this beauty piece of setting.

**Comment by pedrommone** [comment]
I'll work on that.

**Comment by cuducos** [comment]
Personally I don't think `.editorconfig` is of any help in this project.

Most of the code (56.6%) is Python. Python already has a very strict and embraced code style, [pycodestyle](https://pypi.python.org/pypi/pycodestyle) (former [PEP-8](https://www.python.org/dev/peps/pep-0008/)) — and the check for this style [is already in our continuous integration](https://github.com/datasciencebr/jarbas/blob/master/.codeclimate.yml#L2) pipeline.

The seconde most used language here is Elm (41.5%) which also have a well embraced style guide, and a compiler that will stop you if your indentation breaks the app. Moreover most of the Elm community already integrated [elm-format](https://github.com/avh4/elm-format) to run the linter on save.

That said, code styling for 98.1% of the code is already covered. And `Makefile` simple don't work with `spaces` in the place of `tabs`.

That's what I meant when I said `.editorconfig` if not very useful in this context. I see its relevance in other languages (from my experience, JavaScript, PHP, maybe Ruby), but not on Python and Elm repos.

I tend to reject PR #25 because in my point of view it is just another file that is not really helping anyone. But I assume it won't hurt to just add the file.

Any thoughts? Does anybody else here relies on `.editorconfig` settings when coding?

**Comment by pedrommone** [comment]
For me is just a good practice since I handle a lot of different languages everyday.

**Comment by DennyLoko** [comment]
@cuducos I totally agree with you thinking of a person which is already used to code in this languages. It's simply natural for them to follow those standards.

But when a person who just want to help to solve some little bug, and is not used to code in this languages, the `.editorconfig` file helps stick to this patterns without even knowing about them or download a tool.

What I would suggest to @pedrommone is to change the `.editorconfig` file to also support Elm files.

**Comment by cuducos** [comment]
Thanks for the opinion @DennyLoko — let's enhance that PR and merge it ; )

@pedrommone I've never wrote a `.editorconfig` in my whole life, but if tried to add some suggestions in the PR already.
