### ISSUE TITLE
Applying good patterns to project layout

### ISSUE THREAD

**Issue by Leeaandrob** [datasciencebr/jarbas#28]
So, in many projects that I have seen the utilized structure is:

![captura de tela 2016-10-21 as 13 41 16](https://cloud.githubusercontent.com/assets/5758136/19604514/63285f2e-9794-11e6-9fa5-fe93cca05367.png)

Maybe this could to be a issue to fix it?

**Comment by henriquebastos** [comment]
The core rationale of what I do is:

1. The repository directory is the root of all things and contains many
things: the code, docs, utilities, contrib, etc.

2. The django project directory should be one single Python package with
all it's subpackages, submodules, and assets. It should be on the root
repository directory.

3. I follow most of the unix project layout for the surroundings: doc, man,
contrib, etc. But instead of the src directory I use the project name.

4. There should be as little directories as necessary, avoiding
boilerplates to be used.

5. I always start with a core app at the heart of the project to avoid
spanning too many django apps upfront.

6. Having many requirements can be a problem. I have only one. 2 at most if
my test environment is too complex. My development environment should be
equivalent to production to avoid deployment friction.

I use TDD, so refactoring is an assumed  part of the evolution. So I trust
that the inner layout will evolve as needed.

I also like both having static and templates dirs at the project root
directory or using AppDirectoryLoaders. Many of my apps get factored out of
the project as libraries, so that influences me on how I do it.

I hope this explanation helps somehow.

**Comment by henriquebastos** [comment]
Also I just noted the cookie cutter layout separates config from project
code.

For me, personally, this is a critical no go.

There should be only 1 settings.py supporting many instances.

Django mixes project settings with instance settings. However with
python-decouple one can easily extract instance settings to environment
variables.

The main goal is to keep one concise tested codebase that can be seamlessly
loaded into many instance: dev, local, stage, production, demo, playground,
whatever.

**Comment by cuducos** [comment]
Many many thanks, @henriquebastos!

In fact your explanation made it clear for me: we have a lot of good reasons to argue for this architecture.

Personally this is my favorite — and now I understand why.

**Comment by henriquebastos** [comment]
Anytime, dear friend! :)

**Comment by cuducos** [comment]
Closing this Issue since:

* _good_ is such a subjective measure and
* we have good reasons to use the architecture we're using but
* mainly because this Issue was opened in due to a PVT conversation in which we considered using Capistrano to automate  the deploy — this hasn't happened yet and now we're moving towards Docker
