### ISSUE TITLE
Allow more results per page

### ISSUE THREAD

**Issue by gabisurita** [datasciencebr/jarbas#51]
It's is a bit limiting  providing only 10 results per page. I think it would be useful to allow something like:

```
GET /api/document/?year=2015%_limit=100
```

What do you think?

**Comment by cuducos** [comment]
Hi @gabisurita,

Jarbas was created as a tool to visually analyze data from reimbursements found in Serenata de Amor project — it was not suppose to be a tool for browsing or getting tons of data. I understand people might do it, but that was not the initial purpose of this GUI. That said, throwing 100 reimbursements in the screen wasn't a use case scenario. People would get here knowing exactly what they want to look at. Surely this is a utopian scenario, the way people embrace technologies always ignore the purpose technologies were created at first.

Anyway the point is that the API was designed to serve Jarbas, and Jarbas was designed to serve Serenata. That's why things are the way they are. API shows 10 results per page because that made sense for Jarbas purposes.

I get from your suggestion that the API might accidentally help people interested in get access to data. We know the Chamber of Deputies don't to their best to offer data accordingly to the laws. This API can do it better. 

That said this is not the focus of the project at this time, but that could be done quite easily within Django REST Framework (our engine here). Feel free to send a PR if that's useful for you. If it helps I would take a few minutes and read [this](http://www.django-rest-framework.org/api-guide/pagination/#setting-the-pagination-style) (_Setting the pagination style_) and [this](http://www.django-rest-framework.org/api-guide/pagination/#modifying-the-pagination-style) (_Modifying the pagination style_) — probably in a few lines you can setup this new functionality and start testing it!

**Comment by cuducos** [comment]
I must add: If you're just looking for data, I think Serenata de Amor's datasets are the best way to get it. Beautifully compressed CSV are downloaded in the setup of the project (but you can guess the direct download URL from [here](https://github.com/datasciencebr/serenata-de-amor/blob/master/src/fetch_datasets.py)). It would be easier and quicker to get all data, and would save Jarbas resources ; )
